### ISSUE TITLE
sign_gpgkey shouldn't be required when creating/updating publish

### ISSUE THREAD

**Issue by findmyname666** [gopythongo/aptly-api-client#33]
Hi all,
Actually I'm not sure whether the reported 'thing' is bug or feature so bear with me :)
By the way I started to use your lib and it looks good thx.

I'm kind of confuse when publishing snapshot or updating existing one.
There is required option **sign_gpgkey** for package signing, it cannot be empty, but I think it shouldn't be required. Functions in question _def publish, def update_ on object **PublishAPISection**.

When I published snapshot via command-line with curl without gpg key the aptly signs the publish with default gpg key which is stored _locally_. Therefore the lib should allow it as well. If you agree I can prepare diff.

P.S.: There can be passed argument **sign_skip** to functions. It will lead to not signing the publish.

Please let me if you require further information.

**Comment by jdelic** [comment]
I never actually encountered that behavior, but what you say (that aptly will use the default key) makes perfect sense. So I guess you're right and `sign_gpgkey` should actually be optional. It would be great if you filed a PR.

By the way, perhaps I am reading too much into your emphasis on "_locally_", but `sign_gpgkey`, perhaps counter-intuitively, always refers to keys _on the API server_. So you can only pass a GPG key id for keys that the server actually knows about.

Thank you for your message.

**Comment by findmyname666** [comment]
PR created (btw something wrong with one test).

Thanks

**Comment by findmyname666** [comment]
Please let me know whether you need further info.
I would like to have this functionality ASAP :)
Thx a lot

**Comment by jdelic** [comment]
Closed in v0.2.0
