### ISSUE TITLE
method list() in SnapshotAPISection doesn't use sort argument

### ISSUE THREAD

**Issue by findmyname666** [gopythongo/aptly-api-client#54]
Hi there again :)
I noticed that method `def list(self, sort: str = 'name')` doesn't use sort argument at all in the code:
```
    def list(self, sort: str = 'name') -> Sequence[Snapshot]:
        if sort not in ['name', 'time']:
            raise AptlyAPIException("Snapshot LIST only supports two sort modes: 'name' and 'time'. %s is not "
                                    "supported." % sort)
        resp = self.do_get("api/snapshots")
        ret = []
        for rsnap in resp.json():
            ret.append(self.snapshot_from_response(rsnap))
        return ret
```
See code [here](https://github.com/gopythongo/aptly-api-client/blob/master/aptly_api/parts/snapshots.py#L35).
I can create a pull request to fix it if you want ;)

**Comment by jdelic** [comment]
@findmyname666 
That's an embarrassing oversight 😬 

> I can create a pull request to fix it if you want ;)

yes, please!
