### ISSUE TITLE
Using a custom timeout to reach the aptly API

### ISSUE THREAD

**Issue by smutel** [gopythongo/aptly-api-client#58]
Hello,

Is it possible today to specify a custom timeout to reach the aptly API ?
I saw in the function `BaseAPIClient` than there is a timeout parameter.
But not in `Client` class, is-it normal ?

Thanks.

**Comment by jdelic** [comment]
@smutel 
> I saw in the function BaseAPIClient than there is a timeout parameter.
But not in Client class, is-it normal ?

nope, that looks like an incredibly ~stupid~ unfortunate oversight, which I will fix.

**Comment by smutel** [comment]
OK. Thanks.
Is-it possible to add all parameters (not only timeout) of BaseAPIClient ?
