### ISSUE TITLE
About the dependencies pinning

### ISSUE THREAD

**Issue by rsebille** [gopythongo/aptly-api-client#8]
Hello,

Before opening a PR I am starting the discussion here :).
Would you be open to the removal of the strict pinning in the `setup.py` and the `requirements-test.txt`?

`aptly-api-client` is a library not an application, so it's going to be include inside other project, but if this project must pin a dependencies there is going to have a conflict.
If for whatever reason you are not confortable removing the pinning we can loosen it by replacing `==` with `>=`.

**Comment by jdelic** [comment]
I actually do mostly agree. The pinned version dependencies should be removed. Afaict, `aptly-api-client` does not require a speccific minimum version of its runtime dependencies right now.

However, I think it makes sense to pin the versions in `requirements-test.txt` in my opinion. The tests aren't shipped in a distribution and I feel that it's positive to control (and document) the environment the tests were run under.

**Comment by rsebille** [comment]
It totally make sense :).

**Comment by jdelic** [comment]
v0.1.5 removes the pinning from `setup.py`. Thanks for the suggestion.

**Comment by rsebille** [comment]
No problem, thank you for doing it and for the project.
